### ISSUE TITLE
Generate.py throws a keyerror on u'fortios_system_lte_modem'

### ISSUE THREAD

**Issue by emileliason** [fortinet-solutions-cse/ansible_generator#13]
When I run the generate.py script I get stuck on generating module: system_lte_modem

generate.py output:

`python generate.py 

Parsing schema:
Module name: system_vdom
Iteration:0, Schema position: 0
File generated: output/v6.2.1/fortios_system_vdom.py
File generated: output/v6.2.1/fortios_system_vdom_example.yml
File generated: output/v6.2.1/test_fortios_system_vdom.py

Parsing schema:
Module name: system_global
Iteration:1, Schema position: 1
File generated: output/v6.2.1/fortios_system_global.py
File generated: output/v6.2.1/fortios_system_global_example.yml
File generated: output/v6.2.1/test_fortios_system_global.py

Parsing schema:
Module name: system_accprofile
Iteration:2, Schema position: 2
File generated: output/v6.2.1/fortios_system_accprofile.py
File generated: output/v6.2.1/fortios_system_accprofile_example.yml
File generated: output/v6.2.1/test_fortios_system_accprofile.py

Parsing schema:
Module name: system_vdom_link
Iteration:3, Schema position: 3
File generated: output/v6.2.1/fortios_system_vdom_link.py
File generated: output/v6.2.1/fortios_system_vdom_link_example.yml
File generated: output/v6.2.1/test_fortios_system_vdom_link.py

Parsing schema:
Module name: system_switch_interface
Iteration:4, Schema position: 4
File generated: output/v6.2.1/fortios_system_switch_interface.py
File generated: output/v6.2.1/fortios_system_switch_interface_example.yml
File generated: output/v6.2.1/test_fortios_system_switch_interface.py

Parsing schema:
Module name: system_object_tagging
Iteration:5, Schema position: 5
File generated: output/v6.2.1/fortios_system_object_tagging.py
File generated: output/v6.2.1/fortios_system_object_tagging_example.yml
File generated: output/v6.2.1/test_fortios_system_object_tagging.py

Parsing schema:
Module name: system_lte_modem
Iteration:6, Schema position: 6
Traceback (most recent call last):
  File "generate.py", line 238, in <module>
    jinjaExecutor()
  File "generate.py", line 201, in jinjaExecutor
    version_added_json)
  File "generate.py", line 124, in renderModule
    module_version_added = version_added[module_name] 
KeyError: u'fortios_system_lte_modem'
`

schema-file attached.

[fgt_schema.json.txt](https://github.com/fortinet-solutions-cse/ansible_generator/files/3631620/fgt_schema.json.txt)

**Comment by mamunozgonzalez** [comment]
Hi @emileliason,
 the generator is failing because it needs an entry in the file 'version_added.json' for that module: system_lte_modem.

The file is missing something like this:
"fortios_system_lte_modem": 2.10,

You can try to add the module to "version_added.json" and rerun the generator. For the version I have used 2.10 as 2.9 is already out there.

Hope that helps.
