### ISSUE TITLE
Schema creates invalid module name - "fortios_user_tacacs+"

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-solutions-cse/ansible_generator#3]
The manual fix is to rename `fortios_user_tacacs+.py` to `fortios_user_tacacs.py` and then to replace all instances of tacacs+ with tacacs ... *except* in this block:

```
def user_tacacs(data, fos):
    vdom = data['vdom']
    user_tacacs_data = data['user_tacacs']
    filtered_data = filter_user_tacacs_data(user_tacacs_data)
    if user_tacacs_data['state'] == "present":
        return fos.set('user',
                       'tacacs+',
                       data=filtered_data,
                       vdom=vdom)

    elif user_tacacs_data['state'] == "absent":
        return fos.delete('user',
                          'tacacs+',
                          mkey=filtered_data['name'],
                          vdom=vdom)
```

**Comment by mamunozgonzalez** [comment]
I have included a commit to fix this problem. '+' is replaced with 'plus'.  
https://github.com/fortinet-solutions-cse/ansible_generator/commit/6c973b0f10c5f6c55ed76a2fa5ae76af19f1f737

A PR has also been submitted to Ansible including this module:

https://github.com/ansible/ansible/pull/52071

**Comment by mamunozgonzalez** [comment]
I have also included a working example in this commit: https://github.com/fortinet-solutions-cse/ansible_generator/commit/45eba81fbc70ac051549f2e434795c0f55d0e7c9
