### ISSUE TITLE
Delete operation should be idempotent

### ISSUE THREAD

**Issue by mamunozgonzalez** [fortinet-solutions-cse/ansible_generator#4]
Ansible requires that all operations should be idempotent. At the moment, in our modules, this is true for put/set/create/present operations but not for the opposite (delete/absent). If a playbook tries to remove a non existing object it works fine the first time, but it fails the second.

Until this is fixed please handle it with caution.

**Comment by mamunozgonzalez** [comment]
Useful workaround (until this is solved) is given in:
https://github.com/fortinet-solutions-cse/ansible_fgt_modules/issues/8

**Comment by JonTheNiceGuy** [comment]
Is it worth having a "get" event first, then if that returns a valid response, perform the delete?

As a side note having that would make stuff like this possible :grin: :

```
- fortios_firewall_policy:
    host: myhost
    user: myuser
    pass: mypass
    vdom: root
    https: true
    firewall_policy:
    register: the_policy

- debug: var=the_policy
```

**Comment by mamunozgonzalez** [comment]
Yes, but I guess we must implement the fix in the code to have a much better user experience and to comply with full idempotency property. I'll try to add a quick fix (basically ignoring 404 return code)

**Comment by mamunozgonzalez** [comment]
I have created a fix to provide idempotent property on deletes.
Tests seem to be working fine but please try it out and let me know if you find any issue.

Commit: https://github.com/fortinet-solutions-cse/ansible_generator/commit/607590e5ba69410c37113bd2a056d7fcf7cd10d6

**Comment by JonTheNiceGuy** [comment]
Delete action works fine with this model! Thanks!
